### ISSUE TITLE
Sample agents should be in cluster rather than loaded into the DB

### ISSUE THREAD

**Issue by EItanya** [kagent-dev/kagent#121]
In order to unify the different approaches to creating agents we should deploy our pre-created agents to k8s directly via the helm chart. We can add these to a sub-section of the helm-chart so they can be disabled later.

For example:
```
contrib:
  enabled: true
  observability:
    prometheus:
      url: me.com
```
