### ISSUE TITLE
Add support for AWS Bedrock models

### ISSUE THREAD

**Issue by arief-hidayat** [kagent-dev/kagent#183]
I am interested to use with Claude Sonnet 3.7, DeepSeek, and/or Amazon Nova.

**Comment by peterj** [comment]
@arief-hidayat  support for Anthropic models was added in the latest release https://github.com/kagent-dev/kagent/releases/tag/v0.1.11

**Comment by arief-hidayat** [comment]
awesome work. thank you.

I am not familiar with kagent and autogen, but perhaps what I think will be even better is to implement support for autogen semantic kernel. so, kagent will support many other providers. Bedrock is just one of them.
https://microsoft.github.io/autogen/stable//reference/python/autogen_ext.models.semantic_kernel.html
https://github.com/microsoft/semantic-kernel/blob/main/python/samples/concepts/setup/chat_completion_services.py#L24

what do you think?

**Comment by MartinForReal** [comment]
@arief-hidayat ,autogen support litellm https://microsoft.github.io/autogen/stable/user-guide/core-user-guide/cookbook/local-llms-ollama-litellm.html and litellm supports bedrock https://docs.litellm.ai/docs/providers/bedrock FYI

**Comment by sc7565** [comment]
Do we know, when direct Bedrock models would be available for usage?

**Comment by jicowan** [comment]
@EItanya I see that you've added support for Bedrock, however, when I tried creating a new model provider for Bedrock, I got the following error: 
```
Error code: 404 - {'error': {'message': "The model doesn't exist or doesn't support this API. Retry your request with a different model ID.", 'type': 'not_found_error', 'param': None, 'code': 'model_not_found'}}
```
I referenced `anthropic.claude-3-7-sonnet-20250219-v1:0` for the model as you can see in the ModelConfig CR: 
```
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
  name: bedrock-config
  namespace: default
spec:
  apiKeySecret: kagent-bedrock
  apiKeySecretKey: AWS_API_KEY
  model: anthropic.claude-3-7-sonnet-20250219-v1:0
  openAI:
    baseUrl: https://bedrock-runtime.us-west-2.amazonaws.com/openai/v1
  provider: OpenAI
```
I'm not sure where to start to debug this. The last time I tried using kagent, there were a lot fewer pods/deployments.  

I also tried using the litellm workaround that I was using before but the agent returns `connection error`.
