### ISSUE TITLE
Add support for DefaultAzureCredential chain to use instead of OpenAI key

### ISSUE THREAD

**Issue by achaikaJH** [kagent-dev/kagent#217]
Using DefaultAzureCredential paves the way for using any type authentication supported in Azure including service principals and managed identity. These types of credentials in conjunction with Azure RBAC model are way more likely to be used in production environments than static key. 

In this case following model 
```yaml
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: azureopenai-model-config
  namespace: kagent
spec:
  apiKeySecretName: kagent-azureopenai
  apiKeySecretKey: AZURE_OPENAI_API_KEY
  model: gpt-4o-mini
  provider: AzureOpenAI
  azureOpenAI:
    azureEndpoint: "https://<endpointname>.openai.azure.com/"
    apiVersion: "2025-03-01-preview"
    azureDeployment: "gpt-4o-mini"
    azureAdToken: <token>
```
should be able to pickup SPN or Azure Managed Identity credentials from secret and use them to obtain token from `https://cognitiveservices.azure.com/.default` endpoint
