### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rohitrsh** [kagent-dev/kagent#233]
Hey Team,

I am trying to run the kagent with a self-hosted OpenAI-based model. I found that when I specify `baseUrl`, I get a subjected error in the kagent controller.

Here's my configuration and the logs snippet. Can anyone take a look at it and let me know if I am missing anything?

```
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: my-model-config
  namespace: kagent
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecretName: kagent-openai
  model: gpt-4o-mini-2024-07-18
  provider: OpenAI
  openAI:
    baseUrl: "http://example.com/v1/proxy"
---
apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: my-agent-1
  namespace: kagent
spec:
  description: This is the My k8s Agent
  modelConfigRef: my-model-config
  systemMessage: This agent get the events from namespace
  tools:
  - inline:
      provider: kagent.tools.k8s.GetEvents
    type: Inline
```

```
2025-04-10T14:18:06Z    ERROR   Observed a panic        {"controller": "autogenagent", "controllerGroup": "kagent.dev", "controllerKind": "Agent", "Agent": {"name":"my-agent-1","namespace":"kagent"}, "namespace": "kagent", "name": "my-agent-1", "reconcileID": "3f19063a-d688-4056-8c3e-c5402761edc2", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 208 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x24071c8, 0xc000d631a0}, {0x1d973c0, 0x3593980})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:107 +0x112\npanic({0x1d973c0?, 0x3593980?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.createModelClientForProvider(0xc000a10000, {0xc0007a4d20, 0x1f, 0xc0005a8e10?}, 0x1)\n\t/workspace/controller/internal/autogen/autogen_api_translator.go:845 +0x1ad\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).translateGroupChatForTeam(0xc00012eb40, {0x24071c8, 0xc000d631a0}, 0xc000739848, 0x1)\n\t/workspace/controller/internal/autogen/autogen_api_translator.go:237 +0x269\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).TranslateGroupChatForTeam(...)\n\t/workspace/controller/internal/autogen/autogen_api_translator.go:182\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).TranslateGroupChatForAgent(0xc00012eb40, {0x24071c8, 0xc000d631a0}, 0xc000791980)\n\t/workspace/controller/internal/autogen/autogen_api_translator.go:175 +0x25d\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.(*autogenReconciler).reconcileAgents(0xc0004e8000, {0x24071c8, 0xc000d631a0}, {0xc000739b90, 0x1, 0xc000d631a0?})\n\t/workspace/controller/internal/autogen/autogen_reconciler.go:344 +0xa9\ngithub.com/kagent-dev/kagent/go/controller/internal/autogen.(*autogenReconciler).ReconcileAutogenAgent(0xc0004e8000, {0x24071c8, 0xc000d631a0}, {{{0xc000c06b20?, 0x0?}, {0xc000c06b16?, 0x1731d46?}}})\n\t/workspace/controller/internal/autogen/autogen_reconciler.go:65 +0x1b4\ngithub.com/kagent-dev/kagent/go/controller/internal/controller.(*AutogenAgentReconciler).Reconcile(0xc00012ecf0, {0x24071c8, 0xc000d631a0}, {{{0xc000c06b20?, 0x20afdab?}, {0xc000c06b16?, 0x100?}}})\n\t/workspace/controller/internal/controller/autogenagent_controller.go:57 +0x88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000d63110?, {0x24071c8?, 0xc000d631a0?}, {{{0xc000c06b20?, 0x0?}, {0xc000c06b16?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x2424d60, {0x2407200, 0xc00059e820}, {{{0xc000c06b20, 0x6}, {0xc000c06b16, 0xa}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x2424d60, {0x2407200, 0xc00059e820})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288 +0x20d\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 37\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:245 +0x6b5\n"}
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:925
github.com/kagent-dev/kagent/go/controller/internal/autogen.createModelClientForProvider
        /workspace/controller/internal/autogen/autogen_api_translator.go:845
github.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).translateGroupChatForTeam
        /workspace/controller/internal/autogen/autogen_api_translator.go:237
github.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).TranslateGroupChatForTeam
        /workspace/controller/internal/autogen/autogen_api_translator.go:182
github.com/kagent-dev/kagent/go/controller/internal/autogen.(*apiTranslator).TranslateGroupChatForAgent
        /workspace/controller/internal/autogen/autogen_api_translator.go:175
github.com/kagent-dev/kagent/go/controller/internal/autogen.(*autogenReconciler).reconcileAgents
        /workspace/controller/internal/autogen/autogen_reconciler.go:344
github.com/kagent-dev/kagent/go/controller/internal/autogen.(*autogenReconciler).ReconcileAutogenAgent
        /workspace/controller/internal/autogen/autogen_reconciler.go:65
github.com/kagent-dev/kagent/go/controller/internal/controller.(*AutogenAgentReconciler).Reconcile
        /workspace/controller/internal/controller/autogenagent_controller.go:57
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:118
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:328
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249
2025-04-10T14:18:06Z    ERROR   Reconciler error        {"controller": "autogenagent", "controllerGroup": "kagent.dev", "controllerKind": "Agent", "Agent": {"name":"my-agent-1","namespace":"kagent"}, "namespace": "kagent", "name": "my-agent-1", "reconcileID": "3f19063a-d688-4056-8c3e-c5402761edc2", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:341
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:288
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.3/pkg/internal/controller/controller.go:249
```

**Comment by AyoubOrange** [comment]
I am experiencing the same issue when trying to access the LLM through LiteLLM proxy. It seems that changing the baseUrl causes the controller to panic. Below is my current model configuration:
```yaml
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: default-model-config
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
spec:
  apiKeySecretName: {{ .Values.openai.secretName }}
  apiKeySecretKey: {{ .Values.openai.secretKey }}
  model: gpt-4o
  provider: OpenAI
  openAI:
    baseUrl: https://llmproxy.<url>
```
