### ISSUE TITLE
Trouble with ModelConfig CRD After Updating to Include ModelInfo

### ISSUE THREAD

**Issue by AyoubOrange** [kagent-dev/kagent#266]
Hello,

This issue is related to [GitHub Issue #251](https://github.com/kagent-dev/kagent/issues/251). I followed the suggestions from @EItanya to add `model_info` to the model configuration Custom Resource Definition (CRD). Here are the changes I made:

1. **Added a `ModelInfo` struct** in the `go/api/v1alpha1/autogenmodelconfig_types.go` file:

   ```go
   // ModelInfo contains information about the model
   type ModelInfo struct {
       // Indicates if the model supports vision
       // +optional
       Vision bool `json:"vision,omitempty"`

       // Indicates if the model supports function calling
       // +optional
       FunctionCalling bool `json:"functionCalling,omitempty"`

       // Indicates if the model supports JSON output
       // +optional
       JSONOutput bool `json:"jsonOutput,omitempty"`

       // Model family
       // +optional
       Family string `json:"family,omitempty"`
   }
   ```

2. **Updated the `OpenAIConfig` struct** to include `ModelInfo`:

   ```go
   // OpenAIConfig contains OpenAI-specific configuration options
   type OpenAIConfig struct {
       // Base URL for the OpenAI API (overrides default)
       // +optional
       BaseURL string `json:"baseUrl,omitempty"`

       // Organization ID for the OpenAI API
       // +optional
       Organization string `json:"organization,omitempty"`

       // Temperature for sampling
       // +optional
       Temperature string `json:"temperature,omitempty"`

       // Maximum tokens to generate
       // +optional
       MaxTokens int `json:"maxTokens,omitempty"`

       // Top-p sampling parameter
       // +optional
       TopP string `json:"topP,omitempty"`

       // Frequency penalty
       // +optional
       FrequencyPenalty string `json:"frequencyPenalty,omitempty"`

       // Presence penalty
       // +optional
       PresencePenalty string `json:"presencePenalty,omitempty"`

       // Seed value
       // +optional
       Seed *int `json:"seed,omitempty"`

       // N value
       N *int `json:"n,omitempty"`

       // Timeout
       Timeout *int `json:"timeout,omitempty"`

       // Model information
       ModelInfo *ModelInfo `json:"modelInfo,omitempty"`
   }
   ```

3. **Created a model configuration Custom Resource**:

   ```yaml
   apiVersion: kagent.dev/v1alpha1
   kind: ModelConfig
   metadata:
     name: default-model-config
     labels: {{- include "kagent.labels" . | nindent 4 }}
   spec:
     apiKeySecretName: {{ .Values.openai.secretName }}
     apiKeySecretKey: {{ .Values.openai.secretKey }}
     model: openai/gpt-4o
     provider: OpenAI
     openAI:
       baseUrl: <llm-proxy-url>
       modelInfo:
         vision: true
         functionCalling: true
         jsonOutput: true
         family: "O4"
   ```

I successfully installed the new CRD without any issues. However, the problem still persists. I deleted the old CRD and ensured the new one is installed. 

Is there a file that I might have missed? I am still confused about how the resources are sent through the autogen API. Any help would be greatly appreciated, as I am relatively new to Go and writing CRDs.

Thank you!
