### ISSUE TITLE
[FEATURE] Scans container images for vulnerabilities workflow

### ISSUE THREAD

**Issue by dimetron** [kagent-dev/kagent#336]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)

### ❓ Problem Statement / Motivation

We are missing container images scans for vulnerabilities

### 💡 Proposed Solution

- [ ] add [Scans container images for vulnerabilities](https://github.com/marketplace/actions/aqua-security-trivy)
- [ ] add RADME badge for the same 

### 🎯 Affected Service(s)

None

### 🙋 Are you willing to contribute?

- [x] I am willing to submit a PR for this feature

**Comment by dimetron** [comment]
From existing open source scanners we have few options 

- https://github.com/marketplace/actions/anchore-container-scan
- https://github.com/marketplace/actions/aqua-security-trivy



```
      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.6.4
        with:
          image: docker-archive:${{ runner.temp }}/${{ matrix.image }}.tar
          fail-build: false # Optional: set to true to fail the build on vulnerabilities
          severity-cutoff: high # Optional: set the severity cutoff

      - name: Image vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: matrix.image != cli
        with:
          image-ref: '${{ runner.temp }}/${{ matrix.image }}.tar'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

```
