### ISSUE TITLE
[FEATURE] Helm Secret Creation Feature Flag

### ISSUE THREAD

**Issue by Matcham89** [kagent-dev/kagent#345]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)

### 📝 Feature Summary

Create a feature flag for helm secrets 

### ❓ Problem Statement / Motivation

- provider secrets are created by default 
- helm/kagent/templates/secret.yaml comments state that the app container will fail if the secret is NULL. 
- if a user wants to deploy via helm and has a secret manager (external-secrets) there will be conflicts/duplication.
- if a user wants to deploy via helm delcaratively (argocd) & with a secret manager, there will be ownership warnings.

### 💡 Proposed Solution

would be good to have a feature-flag for the secret creation, per provider.

`providers.openAI.secretCreation.enabled`

```yaml
providers:
  default: openAI
  openAI:
    secretCreation: false
    provider: OpenAI
    model: "gpt-4.1-mini"
    apiKeySecretRef: kagent-openai
    apiKeySecretKey: OPENAI_API_KEY
```

```yaml
{{- $dot := . }}
{{- $model := index $dot.Values.providers $dot.Values.providers.default  }}
{{- if $model.secretCreation.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $model.apiKeySecretRef | quote }}
  labels:
    {{- include "kagent.labels" $dot | nindent 4 }}
type: Opaque
data:
  {{/*  to prevent app container to fail with empty key use default - */}}
  {{ $model.apiKeySecretKey | default (printf "%s_API_KEY" $model.provider | upper) }}: {{ $model.apiKey | default "-" | b64enc }}
{{- end }}
```

### 🎯 Affected Service(s)

App Service

### 🙋 Are you willing to contribute?

- [x] I am willing to submit a PR for this feature
