### ISSUE TITLE
[BUG] UI doesn't recognize multiple tools under the same mcpServer field

### ISSUE THREAD

**Issue by peterj** [kagent-dev/kagent#363]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

UI Service

### 🚦 Impact/Severity

No impact (Default)

### 🐛 Bug Description

Deploy an agent with the tools defined like this:

```
 tools:
  - mcpServer:
      toolNames:
      - get_issues
      - get_pull_requests
      - get_user_info
      toolServer: githubmcp
    type: McpServer
```

I was expecting to see all tools in the UI, however, it only showed the first one (get_issues). 

But at least it knows how to invoke all of them (it's a UI issue). Same happens if you go an edit the agent -- you only see 1 tool, even though there are 3 in this case.

### 🔄 Steps To Reproduce

see above

### 📋 Logs

```shell

```

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue
