### ISSUE TITLE
[FEATURE] Clean up the tool-list in the yaml when adding MCP server tools

### ISSUE THREAD

**Issue by christian-posta** [kagent-dev/kagent#370]
From the UI, when we add multiple tools from the same MCP server, it shows up like the following in the YAML:

```yaml
tools:
  - mcpServer:
      toolNames:
      - create_pull_request
      toolServer: server-github
    type: McpServer
  - builtin:
      config:
        docs_base_path: ""
        docs_download_url: https://doc-sqlite-db.s3.sa-east-1.amazonaws.com/
        openai_api_key: ""
      name: kagent.tools.docs.QueryTool
    type: Builtin
  - mcpServer:
      toolNames:
      - create_repository
      toolServer: server-github
    type: McpServer
  - mcpServer:
      toolNames:
      - fork_repository
      toolServer: server-github
    type: McpServer
  - mcpServer:
      toolNames:
      - get_file_contents
      toolServer: server-github
    type: McpServer
  - mcpServer:
      toolNames:
      - get_issue
      toolServer: server-github
    type: McpServer
```

I would think it should show up more like this, where we just list out the tools we want from a specific MCP server:

```yaml
  - mcpServer:
      toolNames:
      - create_pull_request
      - create_branch
      - get_pull_request
      - list_pull_requests
      - get_pull_request_status
      - update_pull_request_branch
      - get_pull_request_comments
      toolServer: server-github
```

ie, the tools shouldn't be added one tool at a time for the same MCP server when we can just list all of the tools we want from the same MCP server.
