### ISSUE TITLE
[BUG] (logs)(manifest) do not expose envs from secrets 

### ISSUE THREAD

**Issue by marcinkubica** [kagent-dev/kagent#497]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

App Service

### 🚦 Impact/Severity

Blocker

### 🐛 Bug Description

envs from secrets are logged in `app`

### 🔄 Steps To Reproduce

create Tool config with envFromSecret
kubectl apply (shows at the start or when we have some dodgy flag so npx fails)
observe envFromSecrets in log

```
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: datadog-mcp-server
  namespace: kagent
spec:
  description: DataDog MCP first
  config:
    stdio:
      args:
      - --ignore-existing
      - datadog-mcp-server
      command: npx
      envFrom:
      - name: DD_API_KEY
        valueFrom:
          type: Secret
          valueRef: datadog
          key: api-key
      - name: DD_APP_KEY
        valueFrom:
          type: Secret
          valueRef: datadog
          key: app-key
      - name: DD_SITE
        valueFrom:
          type: Secret
          valueRef: datadog
          key: dd-site
```

```
2025-06-10 10:13:22.893 | DEBUG    | kagent.tool_servers._stdiomcptoolserver:discover_tools:25 - Discovering tools from stdio server: command='npx' args=['--ignore-existing', 'git+https://github.com/marcinkubica/mcp-server-datadog.git'] env={'DATADOG_API_KEY': 'f6XYZ', 'DATADOG_APP_KEY': 'b8XYZ', 'DDATADOG_SITE': 'datadoghq.eu'} cwd=None encoding='utf-8' encoding_error_handler='strict' type='StdioServerParams' read_timeout_seconds=5
npx: the --ignore-existing argument has been removed.
```

```
2025-06-10 10:29:31.750 | DEBUG    | kagent.tool_servers._stdiomcptoolserver:discover_tools:25 - Discovering tools from stdio server: command='npx' args=['git+https://github.com/marcinkubica/mcp-server-datadog.git'] env={'DATADOG_API_KEY': 'f6XYZ', 'DATADOG_APP_KEY': 'b8XYZ', 'DDATADOG_SITE': 'datadoghq.eu'} cwd=None encoding='utf-8' encoding_error_handler='strict' type='StdioServerParams' read_timeout_seconds=5
n
```

### 🤔 Expected Behavior

do not expose envsFromSecrets into log, ie as value say `envFromSecret`

### 📋 Logs

```shell

```

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue
