### ISSUE TITLE
[BUG] ToolServer logs

### ISSUE THREAD

**Issue by vfarcic** [kagent-dev/kagent#546]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [ ] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

Not Sure

### 🚦 Impact/Severity

No impact (Default)

### 🐛 Bug Description

I have the following `ToolServer`:

```yaml
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: api.githubcopilot.com
  namespace: kagent
spec:
  config:
    sse:
      headers:
        Authorization: Bearer PATH_TOKEN
      timeout: 30s
      url: https://api.githubcopilot.com/mcp/
  description: ""
```

The UI claims `No tools available for this server.`

The following entry of the GitHub remote MCP server works in Cursor.

```json
...
    "github": {
      "url": "https://api.githubcopilot.com/mcp/",
      "headers": {
        "Authorization": "Bearer PATH_TOKEN"
      }
    }
...
```

The real problem is the lack of any meaningful output in the logs of the kagent Pod that would aid in debugging the issue. 

### 🔄 Steps To Reproduce

1. Use the manifest from above to create `ToolServer` (replace `PAT_TOKEN` with the actual GitHub PAT).
2. Observe the output in the UI and in pod logs.

### 📋 Logs

```shell

```

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue
