### ISSUE TITLE
[BUG] External Secret Deletion Breaks ModelConfig Without Status Update

### ISSUE THREAD

**Issue by sbx0r** [kagent-dev/kagent#577]
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [ ] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

Controller Service

### 🚦 Impact/Severity

Minor inconvenience

### 🐛 Bug Description

When users delete Kubernetes secrets that are referenced by ModelConfig resources using `kubectl` or `helm`, the ModelConfig becomes broken but the controller doesn't detect this change.
The ModelConfig Status remains unchanged, showing a healthy state while the resource is actually unusable.

### 🔄 Steps To Reproduce

1. Create a ModelConfig with an API key secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: default
data:
  OPENAI_API_KEY: "abcabc"  # base64 encoded fake key
---
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: gpt4-config
  namespace: default
spec:
  provider: openai
  model: gpt-4
  apiKeySecretRef: "default/openai-secret"
```
2. Check ModelConfig status (should show as ready):
```bash
kubectl get modelconfig gpt4-config -o yaml
# Status shows healthy/ready condition
```
3. Delete the secret externally:
```bash
kubectl delete secret openai-secret -n default
```
4. Check ModelConfig status again:
```bash
kubectl get modelconfig gpt4-config -o yaml
# Status STILL shows healthy/ready - this is the bug!
```
5. Try to use an agent with this ModelConfig - it will fail with unclear errors

### 🤔 Expected Behavior

After secret deletion:
- ModelConfig controller should detect the missing secret
- ModelConfig status should be updated with condition like:
  ```yaml
  status:
    conditions:
    - type: Ready
      status: "False"
      reason: SecretNotFound
      message: "Referenced secret 'default/openai-secret' not found"
  ```
- Users should immediately see the broken state in `kubectl get modelconfig`

### 📱 Actual Behavior

- ModelConfig status shows as healthy/ready
- No indication that the referenced secret is missing
- Agents fail with unclear API errors instead of clear configuration errors
- Users must manually investigate to discover the missing secret

### 🔍 Additional Context

This same issue occurs when:
- Secrets are modified externally with wrong values
- Secret keys are renamed (e.g., `OPENAI_API_KEY` → `API_KEY`)

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue
