### ISSUE TITLE
2. Create `golang` controller to read in CRDs and create autogenstudio JSON, design initial API

### ISSUE THREAD

**Issue by EItanya** [kagent-dev/kagent#7]
This task has 2 major pieces:

- [x] Create `golang` controller to interact with the apiserver
- [ ] Design higher level API for users

**Comment by EItanya** [comment]
Example of API from before switching to studio
```
apiVersion: ai.solo.io/v1alpha1
kind: AutogenAgent
metadata:
  name: k8s_agent
  namespace: autogen-system
  labels:
    team: istio-debug
spec:
  name: "k8s_agent"
  type: "AssistantAgent"
  agent:
    tools:
    - type: BuiltIn
      tool: k8s.get_pods
    - type: BuiltIn
      tool: k8s.get_pod
    - type: BuiltIn
      tool: k8s.get_services
    - type: BuiltIn
      tool: k8s.get_resources
    - type: BuiltIn
      tool: k8s.get_pod_logs
    description: "Run information gathering tasks related to Kubernetes and any resources in the cluster"
    systemMessage: |
      You are an agent specialized in Kubernetes.
      You have access to tools that allow you to interact with the Kubernetes cluster.
```
